### PR TITLE
Initial bsd (Slackware) support for --with-init-script configure option

### PR DESCRIPTION
**Pull request by cwilling**
Signed-off-by: Christoph Willing chris.willing@iinet.net.au

### CODE REVIEW

**Comment by hallyn** [comment]
Sorry, I'm confused by your terminology.  What do you mean by 'bsd' here?

**Comment by cwilling** [comment]
From:
    http://www.slackware.com/config/init.php
"Slackware Linux uses the BSD-style file layout for its system initialization files."

I was just looking for some label that wasn't "slackware", since none of the existing options named an actual distro. If the slackware label is preferred, I'm happy to resubmit.

**Comment by hallyn** [comment]
Ok, thanks.

Not sure... what do you think about "bsdsysv" or "sysv-bsd' ?

I might be being silly, maybe 'bsd' is fine.  I'll take a more detailed look- thanks!

**Comment by cwilling** [comment]
Sorry, not sure how/why that happened. I've recreated the branch correctly - should I send new PR?

**Comment by hallyn** [comment]
Yes, please do.

**Pull request closed without merging**
